#-------------定义RabbitMQ部署-----------------
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rabbit
spec:
 replicas: 1
 selector:
   matchLabels:
     app: rabbit
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: rabbit
   spec:
     containers:
     - image: rabbitmq:3-management
       imagePullPolicy: IfNotPresent
       name: rabbit
       ports:
       - containerPort: 15672
         name: rabbit15672
         protocol: TCP
       - containerPort: 5672 
         name: rabbit5672 
         protocol: TCP
       resources: {}
       volumeMounts:
       - mountPath: /rabbit
         name: rabbit-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # volumes:
      # - name: rabbit-persistent-storage
      #   nfs:
      #    path: /home/nfs-share/rabbit
      #    server: 10.0.33.201
      env:
      - name: RABBITMQ_USERNAME
        value: "hkust"
      - name: RABBITMQ_DEFAULT_PASS
        value: "csit6000o"
      - name: MQ_NODE_IP
        valueFrom:
          fieldRef:  #通过fieldRef引入到env中
            fieldPath: status.hostIP  #注入hostIP信息

---
#-----------------定义rabbit的代理服务--------------
apiVersion: v1
kind: Service
metadata:
 name: rabbit-service
spec:
 ports:
 - name: rabbit15672
   nodePort: 31199
   port: 15672
   protocol: TCP
   targetPort: 15672
 - name: rabbit5672 
   nodePort: 305672
   port: 5672 
   protocol: TCP 
   targetPort: 5672
 selector:
   app: rabbit
 type: NodePort

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: test
#   name: test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: test
#   template:
#     metadata:
#       labels:
#         app: test
#     spec:
#       containers:
#       - env:
#           - name: MY_NODE_IP
#             valueFrom:
#               fieldRef:  #通过fieldRef引入到env中
#                 fieldPath: status.hostIP  #注入hostIP信息
#         name: test
#         image: ziffer99/workflow-opener:0.2