version: "2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmqhost
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=hkust
      - RABBITMQ_DEFAULT_PASS=csit6000o

  minio1:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=hkust
      - MINIO_ROOT_PASSWORD=csit6000o

    volumes:
      - ~/minio/data:/data
    command: server --console-address ":9001" /data
  
  faas:
    image: ziffer99/faas:2.0
    container_name: faas
    links:
      - minio1
    depends_on:
      - minio1
    ports:
      - "60000:60000"

  workflow-opener:
    image: ziffer99/workflow-opener:2.0
    container_name: workflow-opener
    links:
      - rabbitmq
      - faas
    depends_on:
      - rabbitmq
      - faas
  
  file-scanner:
    image: ziffer99/file-scanner:2.0
    container_name: file-scanner
    links:
      - rabbitmq
      - minio1
    depends_on:
      - rabbitmq
      - minio1

