apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: faas
  name: faas
spec:
  ports:
    - name: "60000"
      port: 60000
      targetPort: 60000
  selector:
    io.kompose.service: faas
status:
  loadBalancer: {}
