apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: faas
  name: faas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: faas
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: faas
    spec:
      containers:
        - image: ziffer99/faas:2.0
          name: faas
          ports:
            - containerPort: 60000
          resources: {}
      restartPolicy: Always
status: {}
