apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: file-scanner
  name: file-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-scanner
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: file-scanner
    spec:
      containers:
        - image: ziffer99/file-scanner:1.0
          name: file-scanner
          resources: {}
      restartPolicy: Always
status: {}
