apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: minio1
  name: minio1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: minio1
    spec:
      containers:
        - args:
            - server
            - --console-address
            - :9001
            - /data
          env:
            - name: MINIO_ROOT_PASSWORD
              value: csit6000o
            - name: MINIO_ROOT_USER
              value: hkust
          image: quay.io/minio/minio
          name: minio1
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: minio1-claim0
      restartPolicy: Always
      volumes:
        - name: minio1-claim0
          persistentVolumeClaim:
            claimName: minio1-claim0
status: {}
